<a href="https://colab.research.google.com/github/Siriprapa-tewee/229351/blob/main/Copy_of_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [34]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [4]:
a = torch.tensor(2)
a

tensor(2)

In [5]:
b = torch.tensor(3)
b

tensor(3)

### Convert a tensor to scalar

In [6]:
c = b.item()

3

### Creating 2D tensor

In [7]:
A = torch.tensor([[1, 2], [5, 6]])
A

tensor([[1, 2],
        [5, 6]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [8]:
B = A.numpy()
B

array([[1, 2],
       [5, 6]])

### Convert from numpy array to tensor

In [16]:
C = torch.from_numpy(B)
C

tensor([[1, 2],
        [5, 6]])

## PyTorch and GPU

check if GPU is available

In [17]:
torch.cuda.is_available()

True

In [18]:
C.device

device(type='cpu')

In [19]:
D = c.cuda()
D

tensor([[1, 2],
        [5, 6]], device='cuda:0')

In [20]:
D.device

device(type='cuda', index=0)

In [21]:
C + D #บวกกันไม่ได้

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [22]:
D.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [23]:
E = D.cpu().numpy()
E

array([[1, 2],
       [5, 6]])

## Basic operations

In [24]:
E * 2

array([[ 2,  4],
       [10, 12]])

In [25]:
E - 2

array([[-1,  0],
       [ 3,  4]])

In [26]:
D - 2

tensor([[-1,  0],
        [ 3,  4]], device='cuda:0')

In [27]:
D.cpu() * np.array([1, 2])

/tmp/ipython-input-4124694458.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  D.cpu() * np.array([1, 2])


tensor([[ 1,  4],
        [ 5, 12]])

### Matrix multiplication

In [28]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [29]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [30]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [31]:
A

tensor([[4, 5],
        [8, 9]])

In [32]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [36]:
a = torch.zeros(1, 2, 3 )
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [38]:
b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [39]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
R1 = torch.rand(2, 3)
R1

tensor([[0.0105, 0.6188, 0.6898],
        [0.2499, 0.5281, 0.5903]])

In [41]:
R2 = torch.randn(2, 3)
R2

tensor([[-1.1303, -0.8874,  1.9512],
        [-1.4264, -0.9896, -0.4097]])

## Tensor's shape

### Checking the shape of a tensor

In [42]:
A.shape

torch.Size([2, 2])

In [43]:
A.size()

torch.Size([2, 2])

### Changing the shape of a tensor

In [44]:
u = torch.arange(6)
u.shape

torch.Size([6])

In [45]:
v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [46]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [51]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], dim=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [52]:
d = torch.stack([a, b], axis=1)
d

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [54]:
a

tensor([0, 1, 2, 3])

In [55]:
b

tensor([1, 2, 3, 4])

In [57]:
# concatenate
e = torch.cat([a, b], dim=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [59]:
f = torch.cat([a, b], axis=1) #ทำไม่ได้
f

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### Squeezing a tensor (removing an extra dimension)

In [60]:
A = torch.zeros(1, 2, 3)
B.squeeze()
B

tensor([[1, 4],
        [7, 8]])

In [61]:
B.shape

torch.Size([2, 2])

### Unsqueezing a tensor (adding an extra dimension)

In [62]:
# H.shape = (6, )
C = B.unsqueeze(axis=0)
C.shape

torch.Size([1, 2, 2])

## Indexing

In [63]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [64]:
P[[0, 1, 2], [0, 1, 2]]
P[0:3,0:3]

tensor([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [66]:
torch.inverse(torch.tensor([[2.0, 0.0], [0.0, 5.0]]))

tensor([[0.5000, 0.0000],
        [0.0000, 0.2000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [67]:
A ** 2

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [68]:
A.sum()

tensor(0.)

In [69]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [70]:
import torch

# Create X with shape (200, 7) from N(0,1)
X = torch.randn(200, 7)

# Create b with shape (8, 1) from N(0,1)
# This is consistent with adding an intercept term later to X, making X.shape (200, 8)
b = torch.randn(8, 1)

# Create e with shape (200, 1) from N(0,1)
e = torch.randn(200, 1)

print("X shape:", X.shape)
print("b shape:", b.shape)
print("e shape:", e.shape)

X shape: torch.Size([200, 7])
b shape: torch.Size([8, 1])
e shape: torch.Size([200, 1])


In [71]:
ones = torch.ones(200, 1)
print("Shape of ones tensor:", ones.shape)
print("First 5 elements of ones tensor:\n", ones[:5])

Shape of ones tensor: torch.Size([200, 1])
First 5 elements of ones tensor:
 tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [72]:
X = torch.cat((ones, X), dim=1)
print("Shape of modified X tensor:", X.shape)
print("First 5 rows of modified X tensor:\n", X[:5])

Shape of modified X tensor: torch.Size([200, 8])
First 5 rows of modified X tensor:
 tensor([[ 1.0000,  0.0026,  1.1085, -0.9990, -1.3764,  1.1863,  0.3911, -0.2711],
        [ 1.0000,  0.8097, -0.7506,  0.7666, -0.4942,  0.2550, -2.0061,  0.7454],
        [ 1.0000,  0.6829, -1.2869,  0.6518,  0.7030,  1.1138, -0.6157,  0.1693],
        [ 1.0000, -0.5559,  0.6515, -0.0080,  1.3630,  0.2750, -0.7031,  0.1898],
        [ 1.0000, -2.1883,  0.0704, -0.5820,  0.2203,  0.3126,  1.5725,  0.2424]])


In [73]:
y = torch.matmul(X, b) + e
print("Shape of y tensor:", y.shape)

Shape of y tensor: torch.Size([200, 1])


In [74]:
X_T = X.T
X_T_X = torch.matmul(X_T, X)
X_T_X_inv = torch.inverse(X_T_X)

print("Shape of X_T:", X_T.shape)
print("Shape of X_T_X:", X_T_X.shape)
print("Shape of (X^T X)^-1:", X_T_X_inv.shape)

Shape of X_T: torch.Size([8, 200])
Shape of X_T_X: torch.Size([8, 8])
Shape of (X^T X)^-1: torch.Size([8, 8])


In [75]:
X_T_y = torch.matmul(X_T, y)
b_hat = torch.matmul(X_T_X_inv, X_T_y)

print("Shape of b_hat:", b_hat.shape)
print("First 5 elements of b_hat:\n", b_hat[:5])

Shape of b_hat: torch.Size([8, 1])
First 5 elements of b_hat:
 tensor([[-0.8000],
        [ 0.7396],
        [ 0.3212],
        [-0.9455],
        [ 0.6628]])


In [76]:
y_hat = torch.matmul(X, b_hat)

print("Shape of y_hat:", y_hat.shape)
print("First 5 elements of y_hat:\n", y_hat[:5])

Shape of y_hat: torch.Size([200, 1])
First 5 elements of y_hat:
 tensor([[-1.2892],
        [-1.3769],
        [-1.5519],
        [-0.1649],
        [-2.3700]])


In [77]:
y_np = y.cpu().numpy()
y_hat_np = y_hat.cpu().numpy()

print("Shape of y_np:", y_np.shape)
print("Shape of y_hat_np:", y_hat_np.shape)
print("First 5 elements of y_np:\n", y_np[:5])
print("First 5 elements of y_hat_np:\n", y_hat_np[:5])

Shape of y_np: (200, 1)
Shape of y_hat_np: (200, 1)
First 5 elements of y_np:
 [[-0.64049286]
 [-0.2495274 ]
 [-1.006078  ]
 [-2.5564256 ]
 [-2.4542315 ]]
First 5 elements of y_hat_np:
 [[-1.2891995 ]
 [-1.3768988 ]
 [-1.5518559 ]
 [-0.16487586]
 [-2.370007  ]]


In [78]:
mse = np.mean((y_np - y_hat_np)**2)

print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.93140227
